# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auto_stage_lightGBM_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AutoStageLightGBMDialog(object):
    def setupUi(self, AutoStageLightGBMDialog):
        AutoStageLightGBMDialog.setObjectName("AutoStageLightGBMDialog")
        AutoStageLightGBMDialog.resize(408, 342)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AutoStageLightGBMDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(AutoStageLightGBMDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.OKBt = QtWidgets.QPushButton(AutoStageLightGBMDialog)
        self.OKBt.setObjectName("OKBt")
        self.gridLayout.addWidget(self.OKBt, 1, 0, 1, 1)
        self.CancelBt = QtWidgets.QPushButton(AutoStageLightGBMDialog)
        self.CancelBt.setObjectName("CancelBt")
        self.gridLayout.addWidget(self.CancelBt, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(AutoStageLightGBMDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.AgeCombox = QtWidgets.QComboBox(self.groupBox)
        self.AgeCombox.setObjectName("AgeCombox")
        self.AgeCombox.addItem("")
        self.AgeCombox.addItem("")
        self.AgeCombox.addItem("")
        self.gridLayout_2.addWidget(self.AgeCombox, 3, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.EMGchannelCombox = QtWidgets.QComboBox(self.groupBox)
        self.EMGchannelCombox.setObjectName("EMGchannelCombox")
        self.gridLayout_2.addWidget(self.EMGchannelCombox, 1, 1, 1, 2)
        self.EEGChannelCombox = QtWidgets.QComboBox(self.groupBox)
        self.EEGChannelCombox.setObjectName("EEGChannelCombox")
        self.gridLayout_2.addWidget(self.EEGChannelCombox, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.EEGSiteCombox = QtWidgets.QComboBox(self.groupBox)
        self.EEGSiteCombox.setObjectName("EEGSiteCombox")
        self.EEGSiteCombox.addItem("")
        self.EEGSiteCombox.addItem("")
        self.gridLayout_2.addWidget(self.EEGSiteCombox, 2, 1, 1, 2)
        self.SaveAnnoCheckbox = QtWidgets.QCheckBox(self.groupBox)
        self.SaveAnnoCheckbox.setObjectName("SaveAnnoCheckbox")
        self.gridLayout_2.addWidget(self.SaveAnnoCheckbox, 4, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)

        self.retranslateUi(AutoStageLightGBMDialog)
        QtCore.QMetaObject.connectSlotsByName(AutoStageLightGBMDialog)

    def retranslateUi(self, AutoStageLightGBMDialog):
        _translate = QtCore.QCoreApplication.translate
        AutoStageLightGBMDialog.setWindowTitle(_translate("AutoStageLightGBMDialog", "Dialog"))
        self.OKBt.setText(_translate("AutoStageLightGBMDialog", "Ok"))
        self.CancelBt.setText(_translate("AutoStageLightGBMDialog", "Cancel"))
        self.groupBox.setTitle(_translate("AutoStageLightGBMDialog", "Light GBM Auto Stage options"))
        self.AgeCombox.setItemText(0, _translate("AutoStageLightGBMDialog", "> P56"))
        self.AgeCombox.setItemText(1, _translate("AutoStageLightGBMDialog", "P30 - P56"))
        self.AgeCombox.setItemText(2, _translate("AutoStageLightGBMDialog", "< P30"))
        self.label.setText(_translate("AutoStageLightGBMDialog", "EEG channel:"))
        self.label_3.setText(_translate("AutoStageLightGBMDialog", "Mouse age:"))
        self.label_2.setText(_translate("AutoStageLightGBMDialog", "EEG site:"))
        self.label_8.setText(_translate("AutoStageLightGBMDialog", "EMG channel:"))
        self.EEGSiteCombox.setItemText(0, _translate("AutoStageLightGBMDialog", "Parietal"))
        self.EEGSiteCombox.setItemText(1, _translate("AutoStageLightGBMDialog", "Frontal"))
        self.SaveAnnoCheckbox.setText(_translate("AutoStageLightGBMDialog", "Cover current label"))
from misleep.gui.resources import misleep
