# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auto_stage_causalTransformer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AutoStageCausalTransformerDialog(object):
    def setupUi(self, AutoStageCausalTransformerDialog):
        AutoStageCausalTransformerDialog.setObjectName("AutoStageCausalTransformerDialog")
        AutoStageCausalTransformerDialog.resize(408, 342)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AutoStageCausalTransformerDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(AutoStageCausalTransformerDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.OKBt = QtWidgets.QPushButton(AutoStageCausalTransformerDialog)
        self.OKBt.setObjectName("OKBt")
        self.gridLayout.addWidget(self.OKBt, 1, 0, 1, 1)
        self.CancelBt = QtWidgets.QPushButton(AutoStageCausalTransformerDialog)
        self.CancelBt.setObjectName("CancelBt")
        self.gridLayout.addWidget(self.CancelBt, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(AutoStageCausalTransformerDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.EEGChannelCombox = QtWidgets.QComboBox(self.groupBox)
        self.EEGChannelCombox.setObjectName("EEGChannelCombox")
        self.gridLayout_2.addWidget(self.EEGChannelCombox, 0, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.EMGchannelCombox = QtWidgets.QComboBox(self.groupBox)
        self.EMGchannelCombox.setObjectName("EMGchannelCombox")
        self.gridLayout_2.addWidget(self.EMGchannelCombox, 1, 1, 1, 2)
        self.SaveAnnoCheckbox = QtWidgets.QCheckBox(self.groupBox)
        self.SaveAnnoCheckbox.setObjectName("SaveAnnoCheckbox")
        self.gridLayout_2.addWidget(self.SaveAnnoCheckbox, 2, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)

        self.retranslateUi(AutoStageCausalTransformerDialog)
        QtCore.QMetaObject.connectSlotsByName(AutoStageCausalTransformerDialog)

    def retranslateUi(self, AutoStageCausalTransformerDialog):
        _translate = QtCore.QCoreApplication.translate
        AutoStageCausalTransformerDialog.setWindowTitle(_translate("AutoStageCausalTransformerDialog", "Dialog"))
        self.OKBt.setText(_translate("AutoStageCausalTransformerDialog", "Ok"))
        self.CancelBt.setText(_translate("AutoStageCausalTransformerDialog", "Cancel"))
        self.groupBox.setTitle(_translate("AutoStageCausalTransformerDialog", "Causal Transformer Auto Stage options"))
        self.label.setText(_translate("AutoStageCausalTransformerDialog", "EEG channel:"))
        self.label_8.setText(_translate("AutoStageCausalTransformerDialog", "EMG channel:"))
        self.SaveAnnoCheckbox.setText(_translate("AutoStageCausalTransformerDialog", "Cover current label"))
from misleep.gui.resources import misleep
