# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'misleep/gui/uis/save_data_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveDataDialog(object):
    def setupUi(self, SaveDataDialog):
        SaveDataDialog.setObjectName("SaveDataDialog")
        SaveDataDialog.resize(409, 516)
        self.gridLayout_2 = QtWidgets.QGridLayout(SaveDataDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.OKBtn = QtWidgets.QPushButton(SaveDataDialog)
        self.OKBtn.setObjectName("OKBtn")
        self.gridLayout_2.addWidget(self.OKBtn, 1, 0, 1, 1)
        self.CancelBtn = QtWidgets.QPushButton(SaveDataDialog)
        self.CancelBtn.setObjectName("CancelBtn")
        self.gridLayout_2.addWidget(self.CancelBtn, 1, 1, 1, 1)
        self.ACTimeEdit = QtWidgets.QGroupBox(SaveDataDialog)
        self.ACTimeEdit.setObjectName("ACTimeEdit")
        self.gridLayout = QtWidgets.QGridLayout(self.ACTimeEdit)
        self.gridLayout.setObjectName("gridLayout")
        self.CropDataStartCheckBox = QtWidgets.QCheckBox(self.ACTimeEdit)
        self.CropDataStartCheckBox.setObjectName("CropDataStartCheckBox")
        self.gridLayout.addWidget(self.CropDataStartCheckBox, 2, 0, 1, 1)
        self.CropStartTimeEditor = QtWidgets.QDateTimeEdit(self.ACTimeEdit)
        self.CropStartTimeEditor.setObjectName("CropStartTimeEditor")
        self.gridLayout.addWidget(self.CropStartTimeEditor, 3, 0, 1, 1)
        self.ChannelListView = QtWidgets.QListView(self.ACTimeEdit)
        self.ChannelListView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ChannelListView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ChannelListView.setTabKeyNavigation(True)
        self.ChannelListView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.ChannelListView.setObjectName("ChannelListView")
        self.gridLayout.addWidget(self.ChannelListView, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.ACTimeEdit)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.CropDataEndCheckBox = QtWidgets.QCheckBox(self.ACTimeEdit)
        self.CropDataEndCheckBox.setObjectName("CropDataEndCheckBox")
        self.gridLayout.addWidget(self.CropDataEndCheckBox, 4, 0, 1, 1)
        self.CropEndTimeEditor = QtWidgets.QDateTimeEdit(self.ACTimeEdit)
        self.CropEndTimeEditor.setObjectName("CropEndTimeEditor")
        self.gridLayout.addWidget(self.CropEndTimeEditor, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.ACTimeEdit, 0, 0, 1, 2)

        self.retranslateUi(SaveDataDialog)
        QtCore.QMetaObject.connectSlotsByName(SaveDataDialog)

    def retranslateUi(self, SaveDataDialog):
        _translate = QtCore.QCoreApplication.translate
        SaveDataDialog.setWindowTitle(_translate("SaveDataDialog", "Dialog"))
        self.OKBtn.setText(_translate("SaveDataDialog", "OK"))
        self.CancelBtn.setText(_translate("SaveDataDialog", "Cancel"))
        self.ACTimeEdit.setTitle(_translate("SaveDataDialog", "Save data options"))
        self.CropDataStartCheckBox.setText(_translate("SaveDataDialog", "Crop data - Set Start Time"))
        self.CropStartTimeEditor.setDisplayFormat(_translate("SaveDataDialog", "yyyy/MM/dd HH:mm:ss"))
        self.label_3.setText(_translate("SaveDataDialog", "Select Channels to Save"))
        self.CropDataEndCheckBox.setText(_translate("SaveDataDialog", "Crop data - Set End Time"))
        self.CropEndTimeEditor.setDisplayFormat(_translate("SaveDataDialog", "yyyy/MM/dd HH:mm:ss"))
