# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './misleep/gui/uis/spec_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpecDialog(object):
    def setupUi(self, SpecDialog):
        SpecDialog.setObjectName("SpecDialog")
        SpecDialog.resize(860, 606)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SpecDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(SpecDialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(SpecDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.SpectrogramSaveBt = QtWidgets.QPushButton(self.groupBox_2)
        self.SpectrogramSaveBt.setObjectName("SpectrogramSaveBt")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.SpectrogramSaveBt)
        self.SpectrogramGraphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.SpectrogramGraphicsView.setMinimumSize(QtCore.QSize(800, 200))
        self.SpectrogramGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SpectrogramGraphicsView.setObjectName("SpectrogramGraphicsView")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.SpectrogramGraphicsView)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(SpecDialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.SpectrumGraphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.SpectrumGraphicsView.setMinimumSize(QtCore.QSize(800, 200))
        self.SpectrumGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SpectrumGraphicsView.setObjectName("SpectrumGraphicsView")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.SpectrumGraphicsView)
        self.SpectrumSaveBt = QtWidgets.QPushButton(self.groupBox)
        self.SpectrumSaveBt.setObjectName("SpectrumSaveBt")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.SpectrumSaveBt)
        self.DeltaThetaRatioLabel = QtWidgets.QLabel(self.groupBox)
        self.DeltaThetaRatioLabel.setObjectName("DeltaThetaRatioLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DeltaThetaRatioLabel)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(SpecDialog)
        QtCore.QMetaObject.connectSlotsByName(SpecDialog)

    def retranslateUi(self, SpecDialog):
        _translate = QtCore.QCoreApplication.translate
        SpecDialog.setWindowTitle(_translate("SpecDialog", "Spectrum and Spectrogram"))
        self.groupBox_2.setTitle(_translate("SpecDialog", "Spectrogram"))
        self.SpectrogramSaveBt.setText(_translate("SpecDialog", "Save"))
        self.groupBox.setTitle(_translate("SpecDialog", "Spectrum"))
        self.SpectrumSaveBt.setText(_translate("SpecDialog", "Save"))
        self.DeltaThetaRatioLabel.setText(_translate("SpecDialog", "Delta/Theta ratio: "))
from misleep.gui.resources import misleep
