# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'misleep/gui/uis/state_spectral_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StateSpectralDialog(object):
    def setupUi(self, StateSpectralDialog):
        StateSpectralDialog.setObjectName("StateSpectralDialog")
        StateSpectralDialog.resize(261, 255)
        self.gridLayout_2 = QtWidgets.QGridLayout(StateSpectralDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(StateSpectralDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.BPHigh = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.BPHigh.setDecimals(1)
        self.BPHigh.setMaximum(10000.0)
        self.BPHigh.setSingleStep(0.1)
        self.BPHigh.setProperty("value", 30.0)
        self.BPHigh.setObjectName("BPHigh")
        self.gridLayout.addWidget(self.BPHigh, 5, 1, 1, 1)
        self.BPFilterCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.BPFilterCheckBox.setObjectName("BPFilterCheckBox")
        self.gridLayout.addWidget(self.BPFilterCheckBox, 4, 0, 1, 1)
        self.ChannelSelector = QtWidgets.QComboBox(self.groupBox)
        self.ChannelSelector.setObjectName("ChannelSelector")
        self.gridLayout.addWidget(self.ChannelSelector, 1, 0, 1, 2)
        self.BPLow = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.BPLow.setDecimals(1)
        self.BPLow.setMaximum(100000.0)
        self.BPLow.setSingleStep(0.1)
        self.BPLow.setProperty("value", 0.5)
        self.BPLow.setObjectName("BPLow")
        self.gridLayout.addWidget(self.BPLow, 5, 0, 1, 1)
        self.RejectArtifactCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.RejectArtifactCheckBox.setObjectName("RejectArtifactCheckBox")
        self.gridLayout.addWidget(self.RejectArtifactCheckBox, 7, 0, 1, 1)
        self.RelativeCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.RelativeCheckBox.setObjectName("RelativeCheckBox")
        self.gridLayout.addWidget(self.RelativeCheckBox, 6, 0, 1, 1)
        self.MergeDataCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.MergeDataCheckBox.setObjectName("MergeDataCheckBox")
        self.gridLayout.addWidget(self.MergeDataCheckBox, 8, 0, 1, 1)
        self.ArtThresholdSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.ArtThresholdSpinBox.setDecimals(1)
        self.ArtThresholdSpinBox.setObjectName("ArtThresholdSpinBox")
        self.gridLayout.addWidget(self.ArtThresholdSpinBox, 7, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        self.OKBt = QtWidgets.QPushButton(StateSpectralDialog)
        self.OKBt.setObjectName("OKBt")
        self.gridLayout_2.addWidget(self.OKBt, 1, 0, 1, 1)
        self.CancelBt = QtWidgets.QPushButton(StateSpectralDialog)
        self.CancelBt.setObjectName("CancelBt")
        self.gridLayout_2.addWidget(self.CancelBt, 1, 1, 1, 1)

        self.retranslateUi(StateSpectralDialog)
        QtCore.QMetaObject.connectSlotsByName(StateSpectralDialog)

    def retranslateUi(self, StateSpectralDialog):
        _translate = QtCore.QCoreApplication.translate
        StateSpectralDialog.setWindowTitle(_translate("StateSpectralDialog", "Dialog"))
        self.groupBox.setTitle(_translate("StateSpectralDialog", "State spectral analysis options"))
        self.label.setText(_translate("StateSpectralDialog", "Channel:"))
        self.BPFilterCheckBox.setText(_translate("StateSpectralDialog", "Bandpass filter"))
        self.RejectArtifactCheckBox.setText(_translate("StateSpectralDialog", "Reject artifact"))
        self.RelativeCheckBox.setText(_translate("StateSpectralDialog", "Relative"))
        self.MergeDataCheckBox.setText(_translate("StateSpectralDialog", "Merge data"))
        self.OKBt.setText(_translate("StateSpectralDialog", "OK"))
        self.CancelBt.setText(_translate("StateSpectralDialog", "Cancel"))
